training:
  max_timesteps : 40000        # Max time steps for the whole training process
  batch_size: 32               # Batch size for training
  replay_max_size : 10000       # Number of transitions stored in the replay buffer
  gamma : 0.99                 # Discount factor gamma for reward
  tau : 0.005                  # Target smoothing coefficient
  start_step : 10000           # Number of steps sampling random actions
  noise_policy : 0.2
  noise_clip : 0.5
  noise_explor : 0.1           # Std of Gaussian for noise exploration
  update_freq_policy : 2
  eval_freq : 5000
  num_eval_episodes : 3

optimizer:
  learning_rate: 3e-4

model:
  hidden_size : 128            # Hidden layer number of units